### ISSUE TITLE
Unresolved references

### ISSUE THREAD

**Issue by jhkennedy** [asfadmin/hyp3-lib#104]
There appears to be a few unresolved reference in hyp3-lib

---

- [x]  `cutGeoTiffs.cutFiles` --  2 references to `pixsize` here: 

https://github.com/asfadmin/hyp3-lib/blob/c6ecfa7d0f6b8927cc76cb31bcc0cff17689c590/src/cutGeotiffs.py#L105

I think these are supposed to be references to `pixSize` which is defined latter here:
https://github.com/asfadmin/hyp3-lib/blob/c6ecfa7d0f6b8927cc76cb31bcc0cff17689c590/src/cutGeotiffs.py#L113-L117

@talogan, is that correct?
___

- [x] `get_dem.anti_meridian_kludge` -- 1 reference to `fi` here: 

https://github.com/asfadmin/hyp3-lib/blob/c6ecfa7d0f6b8927cc76cb31bcc0cff17689c590/src/get_dem.py#L122

@talogan do you know what `fi` should be here?

---

- [x]  `par_s1_slc_single.par_s1_slc_single` -- 1 reference to `inFile` here:
https://github.com/asfadmin/hyp3-lib/blob/c6ecfa7d0f6b8927cc76cb31bcc0cff17689c590/src/par_s1_slc_single.py#L91

@talogan should `inFile` be `myfile` here?

---

- [x] `saa_func_lib.is_in_BB` -- 1 reference to `bb` which doesn't exist in scope, or in the module, here:

https://github.com/asfadmin/hyp3-lib/blob/c6ecfa7d0f6b8927cc76cb31bcc0cff17689c590/src/saa_func_lib.py#L336-L340

@talogan should this function be taking `bb` as an input? 

---

**Note:** These should all throw a `NameError` exception if they are executed, but may not be executed for any current hyp3 products (?). 

`inFile` in  `par_s1_slc_single:par_s1_slc_single` is in a try-except block, so if that function is executed, there should be `Unable to fetch precision state vectors... continuing` messages in its log file and will otherwise continue on without stopping.

**Comment by talogan** [comment]
In cutGeotiffs, move the pixSize code block above the main loop on line 80

**Comment by talogan** [comment]
fi is defined on line 111:     demname, fi = args

**Comment by talogan** [comment]
infile should be myfile in par_s1_slc_single.par_s1_slc_single.

This is something that needs to be fixed and delivered as it means that other codes are not operation correctly.

**Comment by talogan** [comment]
The saa_func_lib.py is something that I grabbed from a previous Director who did a bit of coding.  The only routines in there that I've ever used are near the top of the file (gdal open, read, and write) and maybe (?) the utm zone functions.  Anyhow, I'd say you are safe to delete all of the "generic subroutines" found on lines 315 - 356.  I've been meaning to clean saa_func_lib.py up, just haven't gotten around to it...

**Comment by jhkennedy** [comment]
Thanks for you help @talogan
